### ISSUE TITLE
Panic: Illegal AL call

### ISSUE THREAD

**Issue by ramn** [jhasse/ears#3]
Getting a panic "Illegal AL call":

```
OpenAL error : Illegal AL call.
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
```

I'm doing something similar to this:

``` rust
fn main() {
    run();
    run();
}

fn run() {
    let mut music = Music::new("./src/assets/music/tune.ogg").unwrap();
    music.set_looping(true);
    music.play();

    for e in window {
        // break after a while
    }
}
```

When `run` is called the second time it panics.

**Comment by jhasse** [comment]
I can't reproduce this on my machine. Can you try to run with `RUST_BACKTRACE=1` to see where exactly it crashes in ears?

**Comment by ramn** [comment]
Sure!

**Comment by ramn** [comment]
```
OpenAL error : Illegal AL call.
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
stack backtrace:
   1:     0x55b048aea460 - sys::backtrace::tracing::imp::write::haa19c02b4de52f3bG0t
   2:     0x55b048aec905 - panicking::log_panic::_<closure>::closure.41218
   3:     0x55b048aec380 - panicking::log_panic::h527fe484e9de8fe1W7x
   4:     0x55b048ae0b83 - sys_common::unwind::begin_unwind_inner::h51f64b1a34c60827fTs
   5:     0x55b048ae1238 - sys_common::unwind::begin_unwind_fmt::h0845853a1913f45blSs
   6:     0x55b048ae9ac1 - rust_begin_unwind
   7:     0x55b048b18b3f - panicking::panic_fmt::h3967afc085fe8067LFK
   8:     0x55b048b18e18 - panicking::panic::h77d028a733b1a80eiEK
   9:     0x55b0487d474f - option::_<impl>::unwrap::unwrap::h5796935613972209491
                        at ../src/libcore/macros.rs:21
  10:     0x55b048714817 - screen::game_screen::_<impl>::run::ha9dc9faa4d2d9bc05ea
                        at src/screen/game_screen.rs:42
  11:     0x55b0486d6fc2 - main::h71f262e6cb266188Zqa
                        at src/main.rs:29
  12:     0x55b048aec124 - sys_common::unwind::try::try_fn::h11901883998771707766
  13:     0x55b048ae9908 - __rust_try
  14:     0x55b048aebdc6 - rt::lang_start::hc150f651dd2af18b44x
  15:     0x55b048715259 - main
  16:     0x7fd7c86cba3f - __libc_start_main
  17:     0x55b0486d68f8 - _start
  18:                0x0 - <unknown>
AL lib: (WW) FreeContext: (0x55b04ad1ea40) Deleting 1 Source(s)
AL lib: (WW) FreeDevice: (0x55b04ad21070) Deleting 4 Buffer(s)
```

That line 42 is:

```
    Music::new("./src/assets/music/tune.ogg").unwrap();
```

**Comment by jhasse** [comment]
What operation system are you running?

Creating to looping Musics works fine for me on Linux.

**Comment by ramn** [comment]
Running Linux, Ubuntu 16.10. Same issue if I remove the looping.

It seems like letting the music object go out of scope (dropping when function returns), then create the same thing again is problematic. Does it leave stuff behind when dropping?

**Comment by jhasse** [comment]
I guess you mean 15.10, right? :D

I'll retry to reproduce by also dropping my first Music object.

> Does it leave stuff behind when dropping?

Yes, I think it does. But it shouldn't ;)

**Comment by ramn** [comment]
Haha yes 15.10 :)

**Comment by jhasse** [comment]
Okay I think I fixed it. Can you try 0.3.3?

**Comment by ramn** [comment]
My cargo can't find version 0.3.3

**Comment by ramn** [comment]
Caused by:

failed to unpack package `ears v0.3.3`

**Comment by ramn** [comment]
Was it too many keywords? Must bump version again?

**Comment by jhasse** [comment]
Strange. I've bumped the version again. Can you try again with 0.3.4?

**Comment by ramn** [comment]
Tested against gitrepo master - works now!

Awesome job, you're quick!

**Comment by ramn** [comment]
Cargo can download 0.3.4, thx
